// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';

const SUPABASE_URL = "https://bhegfielkaywgoldpcby.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJoZWdmaWVsa2F5d2dvbGRwY2J5Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTg4MjYxNzcsImV4cCI6MjA3NDQwMjE3N30.vN3sCV1opkDyfonF8y6p6KpCfVJS9yPyqo5MpuWTTYs";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);